### ISSUE TITLE
Value for memory in "Custom GPU and RAM Tweaks" is confusing

### ISSUE THREAD

**Issue by jovan2009** [emylfy/simplify11#1]
Hi, I just ran the script and I'm not sure what to choose at "[2] Custom GPU and RAM Tweaks' dialogue.
```
`What size of RAM do you have?

[1] 4GB
[2] 6GB
[3] 8GB
[4] 16GB
[5] 32GB
[6] 64GB
[7] Skip if Unsure
>`
```
I have 4GB of ram, so I typed 1. But the feedback is confusing:
```
`What size of RAM do you have?

[1] 4GB
[2] 6GB
[3] 8GB
[4] 16GB
[5] 32GB
[6] 64GB
[7] Skip if Unsure
> 1
The operation completed successfully.
Successfully applied tweak for 1GB RAM.
Press any key to continue . . .`
```
If I type 4, corresponding to 16 GB I get this:
```
What size of RAM do you have?

[1] 4GB
[2] 6GB
[3] 8GB
[4] 16GB
[5] 32GB
[6] 64GB
[7] Skip if Unsure
> 4
The operation completed successfully.
Successfully applied tweak for 4GB RAM.
Press any key to continue . . .
```
I'm not sure what should I choose.

**Comment by emylfy** [comment]
The tweak was applied correctly based on your selection. However, there was a mistake in the feedback message, which displayed the option number instead of the actual RAM size. This issue has been fixed in the latest commit. Very grateful for the feedback

![image](https://github.com/user-attachments/assets/b71fe9b5-b38b-43ab-ab83-1fd4e95ed8c4)
